from fastapi import APIRouter, status, HTTPException, Depends
from fastapi.security import OAuth2PasswordRequestForm, OAuth2PasswordBearer
from uuid import uuid4

from ..utils.hashing import (
    get_hashed_password, create_access_token, create_refresh_token, verify_password)

from ..models.token import TokenSchema
from ..models.user import UserOut, UserAuth, SystemUser, UserSignup, PasswordReset
from ..models.user import User
from ..config.database import db
from ..config.deps import get_current_user
from ..utils.otp import verify_token

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/login")

auth = APIRouter()


@auth.post("/signup", response_model=UserOut)
async def signup(userInfo: UserSignup):

    # Check if user already exists
    if db.find_one({"roll_no": userInfo.roll_no}):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="User already exists",
        )

    # Hash password
    hashed_password = get_hashed_password(userInfo.password)

    # # Create user
    # user : User = {
    #     "id": str(uuid4()),
    #     "roll_no": userInfo.roll_no,
    #     "name": userInfo.name,
    #     "password": hashed_password,
    #     "phone_number": userInfo.phone_number,
    #     "gender"   : userInfo.gender,
    # }

    user: UserSignup = UserSignup(**userInfo.dict())

    user.password = hashed_password
    user.id = str(uuid4())

    # Insert user
    db.insert_one(user)

    # Return user
    return user


@auth.get('/me', response_model=UserOut)
async def me(current_user: SystemUser = Depends(get_current_user)):
    return current_user


@auth.post("/reset-password")
async def reset_password(password_reset: PasswordReset):
    user = db.find_one({"roll_no": password_reset.roll_no})
    # check if the user has a valid token (generated by the otp route)
    verified, messsage = verify_token(password_reset.roll_no, password_reset.verification_token)
    if not verified:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=messsage,
        )

    if not user:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="User not found",
        )

    # Hash password
    hashed_password = get_hashed_password(password_reset.password)

    stored_user = User(**user)
    updated_user = stored_user.copy()
    updated_user.password = hashed_password

    # response = db.update_one({"roll_no": password_reset.roll_no}, {
    #                          "$set": updated_user.dict()})

    # if response:
    #     return updated_user
    # else:
    #     return {"detail": "User not found"}
